site_name: Deon's Documentation

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
- pymdownx.superfences
- pymdownx.tabbed
- admonition
- pymdownx.tabbed
- toc:
  permalink: true

plugins:
- search
- roamlinks
- include-markdown
